//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class producten
    {
        public producten()
        {
            this.usersproductens = new HashSet<usersproducten>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public double prijs { get; set; }
        public int aantal { get; set; }

        public virtual HashSet<usersproducten> usersproductens { get; set; }
    }
}
