//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersproducten
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int productid { get; set; }
        public int aantal { get; set; }
    
        public virtual producten producten { get; set; }
        public virtual user user { get; set; }
    }
}
