
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.wcfservicelibrary1.ArrayOfproducten;
import org.datacontract.schemas._2004._07.wcfservicelibrary1.ArrayOfusersproducten;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPracticumService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.wcfservicelibrary1.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IPracticumService {


    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/IPracticumService/Register")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterResponse")
    public String register(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "LogIn", action = "http://tempuri.org/IPracticumService/LogIn")
    @WebResult(name = "LogInResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LogIn", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogIn")
    @ResponseWrapper(localName = "LogInResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogInResponse")
    public Boolean logIn(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfservicelibrary1.ArrayOfproducten
     */
    @WebMethod(action = "http://tempuri.org/IPracticumService/getProducts")
    @WebResult(name = "getProductsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductsResponse")
    public ArrayOfproducten getProducts(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param volume
     * @param password
     * @param productId
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BuyProduct", action = "http://tempuri.org/IPracticumService/BuyProduct")
    @WebResult(name = "BuyProductResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BuyProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyProduct")
    @ResponseWrapper(localName = "BuyProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyProductResponse")
    public String buyProduct(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "productId", targetNamespace = "http://tempuri.org/")
        Integer productId,
        @WebParam(name = "volume", targetNamespace = "http://tempuri.org/")
        Integer volume);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfservicelibrary1.ArrayOfusersproducten
     */
    @WebMethod(operationName = "GetPurchases", action = "http://tempuri.org/IPracticumService/GetPurchases")
    @WebResult(name = "GetPurchasesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPurchases", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPurchases")
    @ResponseWrapper(localName = "GetPurchasesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPurchasesResponse")
    public ArrayOfusersproducten getPurchases(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "GetSaldo", action = "http://tempuri.org/IPracticumService/GetSaldo")
    @WebResult(name = "GetSaldoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSaldo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSaldo")
    @ResponseWrapper(localName = "GetSaldoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSaldoResponse")
    public Double getSaldo(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
