
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PracticumService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733/Design_Time_Addresses/WcfServiceLibrary1/Service1/?wsdl")
public class PracticumService
    extends Service
{

    private final static URL PRACTICUMSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRACTICUMSERVICE_EXCEPTION;
    private final static QName PRACTICUMSERVICE_QNAME = new QName("http://tempuri.org/", "PracticumService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8733/Design_Time_Addresses/WcfServiceLibrary1/Service1/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRACTICUMSERVICE_WSDL_LOCATION = url;
        PRACTICUMSERVICE_EXCEPTION = e;
    }

    public PracticumService() {
        super(__getWsdlLocation(), PRACTICUMSERVICE_QNAME);
    }

    public PracticumService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRACTICUMSERVICE_QNAME, features);
    }

    public PracticumService(URL wsdlLocation) {
        super(wsdlLocation, PRACTICUMSERVICE_QNAME);
    }

    public PracticumService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRACTICUMSERVICE_QNAME, features);
    }

    public PracticumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PracticumService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPracticumService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPracticumService")
    public IPracticumService getBasicHttpBindingIPracticumService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPracticumService"), IPracticumService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPracticumService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPracticumService")
    public IPracticumService getBasicHttpBindingIPracticumService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPracticumService"), IPracticumService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRACTICUMSERVICE_EXCEPTION!= null) {
            throw PRACTICUMSERVICE_EXCEPTION;
        }
        return PRACTICUMSERVICE_WSDL_LOCATION;
    }

}
